#!/usr/bin/env python3
"""
Patch install.sh files NOT covered by generate-packs.mjs with the Jobs-fix
(first_use_demo aware closing hint). Idempotent: skips files already patched.

Designed for the 11 packs sourced from the Python sync pipeline (data-analyst,
executive-strategist, research-analyst, spellbook-*) whose install.sh is not
regenerated by generate-packs.mjs.

Authority: Jobs R2 audit 2026-05-16 — fleet-wide leverage point.
"""

import sys
from pathlib import Path

PACKS_DIR = Path(__file__).resolve().parent.parent / "web" / "public" / "packs"

# Marker that identifies the closing line to insert AFTER
ANCHOR = 'echo "  OK Installed $N artifacts under $TARGET_DIR"'

# Idempotency marker — if any install.sh already contains this, skip
IDEMPOTENT_MARKER = "# Jobs-fix (2026-05-16 audit)"

JOBS_FIX_BLOCK = '''
# Jobs-fix (2026-05-16 audit): if manifest declares first_use_demo, print as next-step hint.
# WHY broad try/except: this code runs INSIDE the cohort's install.sh on their machine.
# If manifest.json is malformed or python json decoding raises any exception, we MUST NOT
# abort the install with a stack trace — the cohort already has 20/20 artifacts on disk;
# the closing hint is a nice-to-have. Silent fallback to the no-hint path is intentional.
HINT=$(python3 - "$MANIFEST" <<'PYEOF2'
import json, sys
try:
    m = json.load(open(sys.argv[1]))
    fud = m.get("first_use_demo") or {}
    cmd = fud.get("command", "").strip()
    if cmd:
        print(cmd)
except Exception:
    pass  # silent fallback to legacy closing hint — see WHY comment in patch source
PYEOF2
)
if [ -n "$HINT" ]; then
  echo ""
  echo "  Now try:"
  echo "    $HINT"
fi
'''


def patch_one(install_sh: Path) -> str:
    text = install_sh.read_text(encoding="utf-8")
    if IDEMPOTENT_MARKER in text:
        return "ALREADY_PATCHED"
    if ANCHOR not in text:
        return "NO_ANCHOR"
    new_text = text.replace(ANCHOR, ANCHOR + JOBS_FIX_BLOCK, 1)
    install_sh.write_text(new_text, encoding="utf-8")
    return "PATCHED"


def main():
    results = {}
    for pack_dir in sorted(PACKS_DIR.iterdir()):
        if not pack_dir.is_dir():
            continue
        install_sh = pack_dir / "install.sh"
        if not install_sh.is_file():
            results[pack_dir.name] = "NO_INSTALL"
            continue
        results[pack_dir.name] = patch_one(install_sh)

    for slug, status in results.items():
        print(f"  {slug:<32}  {status}")

    counts = {}
    for v in results.values():
        counts[v] = counts.get(v, 0) + 1
    print()
    print("Summary:", counts)


if __name__ == "__main__":
    main()
